# Generated by Django 2.1.1 on 2018-10-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('nocontrol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField(verbose_name=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('calle', models.CharField(max_length=50)),
                ('numero_exterior', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('clave_oficial', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id_estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='localidad',
            fields=[
                ('id_localidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id_municipio', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=70)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_alumnos.estado')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_alumnos.municipio'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_alumnos.carrera'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_alumnos.localidad'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_alumnos.rol'),
        ),
    ]
